sudo: required
services:
  - docker

before_install:
  - docker build -t saravana/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true saravana/react-test npm test

after_success:
  - docker build -t khkz211/multi-client ./client
  - docker build -t khkz211/multi-nginx ./nginx
  - docker build -t khkz211/multi-server ./server
  - docker build -t khkz211/multi-worker ./worker

# Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
# Take the images and push them in Docker Hub
  - docker push khkz211/multi-client
  - docker push khkz211/multi-nginx
  - docker push khkz211/multi-server
  - docker push khkz211/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-container"
  env: "MultiContainer-env"
  bucket_name: "elasticbeanstalk-us-east-2-569870974288"
  bucket_path: "multi-container"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"